# Generated by Django 4.1.3 on 2022-12-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=1000,
                    ),
                ),
                ("result", models.IntegerField(null=True)),
                ("white_timer", models.TimeField()),
                ("black_timer", models.TimeField()),
                ("moves_made", models.IntegerField(default=0)),
                ("last_move_time", models.DateTimeField(null=True)),
                (
                    "black_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="black_player",
                        to="chess_game.player",
                    ),
                ),
                (
                    "white_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="white_player",
                        to="chess_game.player",
                    ),
                ),
            ],
        ),
    ]
