# Generated by Django 4.1.3 on 2023-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=1000,
                    ),
                ),
                ("result", models.IntegerField(null=True)),
                ("increment", models.IntegerField(default=0)),
                ("white_timer", models.TimeField()),
                ("black_timer", models.TimeField()),
                ("moves_made", models.IntegerField(default=0)),
                ("last_move_time", models.DateTimeField(null=True)),
                ("time_control", models.CharField(default="blitz", max_length=10)),
            ],
        ),
    ]
