# Generated by Django 4.1.4 on 2023-01-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="player",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("rating", models.IntegerField(default=2000)),
                ("country", models.CharField(default="FIDE", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ReadyToPlay",
            fields=[
                (
                    "player",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="player",
                        serialize=False,
                        to="chess_game.player",
                    ),
                ),
                (
                    "chosen_time_mode",
                    models.CharField(default="00:03:00|2", max_length=20),
                ),
                ("wait_start", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=1000,
                    ),
                ),
                ("result", models.IntegerField(null=True)),
                ("increment", models.IntegerField(default=0)),
                ("white_timer", models.TimeField()),
                ("black_timer", models.TimeField()),
                ("moves_made", models.IntegerField(default=0)),
                ("last_move_time", models.DateTimeField(null=True)),
                ("time_control", models.CharField(default="blitz", max_length=10)),
                (
                    "black_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="black_player",
                        to="chess_game.player",
                    ),
                ),
                (
                    "white_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="white_player",
                        to="chess_game.player",
                    ),
                ),
            ],
        ),
    ]
