# Generated by Django 4.1.3 on 2022-11-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="fen",
            field=models.CharField(
                default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                max_length=1000,
            ),
        ),
    ]
