# Generated by Django 4.1.3 on 2022-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_game", "0002_chessgame_fen"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="moves_made",
            field=models.IntegerField(default=0),
        ),
    ]
