# Generated by Django 4.1.3 on 2022-12-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_game", "0003_chessgame_moves_made"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="last_move_time",
            field=models.DateTimeField(null=True),
        ),
    ]
