# Generated by Django 4.1.3 on 2022-12-25 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chess_game", "0004_chessgame_last_move_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="country",
            field=models.CharField(default="FIDE", max_length=50),
        ),
        migrations.AlterField(
            model_name="player",
            name="id",
            field=models.OneToOneField(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="player",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="rating",
            field=models.IntegerField(default=2000),
        ),
    ]
